[package]
name = "selfdylib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
# 重要，否则 Rust 不会生成兼容 C ABI 的动态库
crate-type = ["cdylib"]

[dependencies]
# 重要，创建 Emacs 动态模块的关键依赖
emacs = "0.19"
git2 = "0.18"